import type { Bilingual, Study } from './studies';
const text = (en: string, et: string): Bilingual => ({ en, et });
const choice = (id: string, fits: boolean, en: string, et: string) => ({ id, fits, reason: text(en, et) });
export const evaluationCards = [
  { id: 'compare-tasks', term: text('Compare realistic tasks', 'Võrdle realistlikke ülesandeid'), definition: text('Compare task success, time, and errors against the current approach; use participants’ explanations to interpret the results.', 'Võrdle ülesannete edukust, aega ja vigu praeguse lahendusega ning tõlgenda tulemusi osalejate selgituste abil.') },
  { id: 'inclusive-evaluation', term: text('Evaluate accessibility together', 'Hinda ligipääsetavust ühiselt'), definition: text('Let affected users help define success, test realistic tasks using their access tools, and combine their feedback with an accessibility review.', 'Lase mõjutatud kasutajatel määratleda edu, katsetada realistlikke ülesandeid oma abivahenditega ning ühenda nende tagasiside ligipääsetavuse ülevaatusega.') },
  { id: 'requirements-evaluation', term: text('Evaluate agreed requirements', 'Hinda kokkulepitud nõudeid'), definition: text('Test agreed workflows and quality criteria with intended users, compare with the existing process, and document design lessons.', 'Katseta sihtkasutajatega kokkulepitud töövooge ja kvaliteedikriteeriume, võrdle senise protsessiga ning dokumenteeri disainialased õppetunnid.') },
  { id: 'count-features', term: text('Count implemented features', 'Loenda valminud funktsioonid'), definition: text('Use the number of completed features as the only measure of success.', 'Kasuta ainsa edumõõdikuna valminud funktsioonide arvu.') },
];
const featureFeedback = choice('count-features', false, 'Feature count measures output, not whether users can solve the problem. Choose evidence tied to the brief’s goals.', 'Funktsioonide arv mõõdab väljundit, mitte seda, kas kasutajad saavad probleemi lahendada. Vali ülesande eesmärkidega seotud tõendid.');
export const computingStudies: Study[] = [
  {
    id: 'room-finder', title: text('Campus room finder', 'Õpperuumide otsing'),
    question: text('Does a room-finder app help students find a suitable study room faster, and what difficulties remain?', 'Kas ruumiotsingu rakendus aitab õpilastel sobiva õpperuumi kiiremini leida ja millised raskused jäävad?'),
    brief: text('Build a prototype showing room availability and facilities. Compare realistic room-search tasks with the current process, recording success and time, then interview students about difficulties. Integrate numerical summaries with themes from the interviews. The quantitative analysis is placed for you.', 'Loo prototüüp, mis näitab ruumide saadavust ja varustust. Võrdle realistlikke ruumiotsingu ülesandeid senise protsessiga, talletades edukuse ja aja, ning intervjueeri õpilasi raskuste kohta. Lõimi arvulised kokkuvõtted intervjuude teemadega. Kvantitatiivne analüüs on ette antud.'),
    fixed: { paradigm: 'pragmatism', analysis: 'descriptive-statistics' },
    slots: {
      paradigm: [choice('pragmatism', true, 'The practical problem guides the combination of performance measures and user explanations.', 'Praktiline probleem suunab sooritusnäitajate ja kasutajate selgituste ühendamist.')],
      methodology: [choice('mixed-methods', true, 'The brief requires integration: explain task results using interview themes, rather than reporting two disconnected datasets.', 'Ülesanne nõuab lõimimist: selgita ülesannete tulemusi intervjuude teemade abil, mitte ära esita kaht eraldiseisvat andmestikku.'), choice('experimental-design', false, 'An experiment could test a feature’s effect, but this brief centres integration of numerical and qualitative evidence. A comparison alone does not establish an experiment.', 'Eksperiment võiks kontrollida funktsiooni mõju, kuid siin on keskne arvuliste ja kvalitatiivsete tõendite lõimimine. Võrdlus üksi ei tähenda eksperimenti.')],
      collection: [choice('usability-testing', true, 'Observe students attempting room-search tasks and record success, time, and problems with the interface.', 'Jälgi õpilasi ruumiotsingu ülesandeid täitmas ning talleta edukus, aeg ja liidese probleemid.'), choice('questionnaire', false, 'Opinions from a questionnaire do not replace observing whether students can actually find a room.', 'Küsimustiku arvamused ei asenda vaatlust selle kohta, kas õpilased tegelikult leiavad ruumi.')],
      collection2: [choice('interview', true, 'Follow-up interviews help explain confusing results and remaining difficulties. Develop themes and relate them to task performance.', 'Järelintervjuud aitavad selgitada ebaselgeid tulemusi ja allesjäänud raskusi. Arenda teemad ning seosta need ülesannete sooritusega.'), choice('requirements-interview', false, 'Requirements interviews help define a future system. Here the conversation explains difficulties after using the prototype.', 'Nõuete intervjuud aitavad määratleda tulevast süsteemi. Siin selgitab vestlus prototüübi kasutamisel tekkinud raskusi.')],
      analysis: [choice('descriptive-statistics', true, 'Summarise task success and time, then integrate these summaries with interview themes. These summaries alone do not prove a causal effect.', 'Võta kokku ülesannete edukus ja aeg ning lõimi kokkuvõtted intervjuude teemadega. Need kokkuvõtted üksi ei tõesta põhjuslikku mõju.')],
      evaluation: [choice('compare-tasks', true, 'Use comparable tasks and account for task order and practice effects. Faster completion matters only if students also find a suitable room; document limitations.', 'Kasuta võrreldavaid ülesandeid ning arvesta järjekorra ja harjutamise mõjuga. Kiirem sooritus loeb ainult siis, kui leitakse sobiv ruum; dokumenteeri piirangud.'), featureFeedback],
    },
  },
  {
    id: 'accessible-planner', title: text('Accessible course planner', 'Ligipääsetav õppeplaan'),
    question: text('How can students who face accessibility barriers shape a course planner that works for them?', 'Kuidas saavad ligipääsetavustakistusi kogevad õpilased kujundada enda jaoks toimiva õppeplaneerija?'),
    brief: text('Develop a coursework planner with students who use different access tools. They share decisions about priorities and success criteria. Work in cycles: agree a change, build it, try real planning tasks together, and reflect. Analyse their accounts of barriers after each cycle.', 'Arenda õppeülesannete planeerijat koos eri abivahendeid kasutavate õpilastega. Nad osalevad prioriteetide ja edukriteeriumide otsustamises. Tööta tsüklites: leppige muutus kokku, looge see, proovige koos tegelikke planeerimisülesandeid ja reflekteerige. Analüüsi iga tsükli järel takistuste kirjeldusi.'),
    fixed: { methodology: 'action-research' },
    slots: {
      paradigm: [choice('critical', true, 'Shared decisions and reducing exclusion support a transformative orientation. Students are partners in shaping the research.', 'Ühine otsustamine ja tõrjutuse vähendamine toetavad transformatiivset suunitlust. Õpilased on uuringu kujundamisel partnerid.'), choice('interpretivism', false, 'Understanding experience matters, but this brief also explicitly shares decision-making power to change exclusionary practice.', 'Kogemuse mõistmine on oluline, kuid see ülesanne jagab ka otsustusõigust tõrjuva praktika muutmiseks.')],
      methodology: [choice('action-research', true, 'This is a participatory form of action research: students help plan, act, evaluate, and reflect through repeated cycles.', 'See on osaluspõhine tegevusuuring: õpilased aitavad korduvates tsüklites kavandada, tegutseda, hinnata ja reflekteerida.')],
      collection: [choice('usability-testing', true, 'Try realistic planning tasks with participants using their own access tools, and record obstacles and comments.', 'Katseta osalejatega realistlikke planeerimisülesandeid nende abivahenditega ning talleta takistused ja kommentaarid.'), choice('questionnaire', false, 'A questionnaire can add feedback, but cannot show the interaction barriers encountered during real planning tasks.', 'Küsimustik võib lisada tagasisidet, kuid ei näita tegelike planeerimisülesannete ajal tekkivaid suhtlustakistusi.')],
      analysis: [choice('thematic-analysis', true, 'Develop patterns in participants’ accounts of barriers and discuss interpretations with them to inform the next cycle.', 'Arenda osalejate takistuste kirjeldustes mustreid ja aruta tõlgendusi nendega järgmise tsükli kavandamiseks.'), choice('descriptive-statistics', false, 'Counts could complement the study, but this slot asks you to interpret accounts of barriers rather than numerical measurements.', 'Arvulised näitajad võiksid uuringut täiendada, kuid siin tuleb tõlgendada takistuste kirjeldusi, mitte arvulisi mõõtmisi.')],
      evaluation: [choice('inclusive-evaluation', true, 'Combine user-defined goals and testing with an accessibility review. Neither one participant’s success nor an automated check establishes accessibility for everyone.', 'Ühenda kasutajate määratletud eesmärgid ja testimine ligipääsetavuse ülevaatusega. Ühe osaleja edu ega automaatkontroll ei tõenda ligipääsetavust kõigile.'), featureFeedback],
    },
  },
  {
    id: 'equipment-lending', title: text('Equipment lending system', 'Seadmete laenutussüsteem'),
    question: text('What application design helps students borrow lab equipment while reducing staff effort?', 'Milline rakenduse disain aitab õpilastel laboriseadmeid laenata ja vähendab töötajate ajakulu?'),
    brief: text('The lab uses a spreadsheet: students cannot see availability and staff chase overdue returns. Build a reservation and return prototype. First establish stakeholder needs, then test realistic workflows. Summarise completion times and errors; evaluate agreed criteria against the existing process and report reusable design lessons.', 'Labor kasutab tabelit: õpilased ei näe saadavust ja töötajad tegelevad hilinenud tagastustega. Loo broneerimise ja tagastamise prototüüp. Selgita esmalt osapoolte vajadused ning katseta realistlikke töövooge. Võta kokku sooritusajad ja vead; hinda kokkulepitud kriteeriume senise protsessiga võrreldes ning esita taaskasutatavad disainialased õppetunnid.'),
    fixed: { paradigm: 'pragmatism', collection2: 'usability-testing' },
    slots: {
      paradigm: [choice('pragmatism', true, 'This study takes a practical problem-focused stance. Design science can also be justified through other philosophical positions.', 'See uuring lähtub praktilisest probleemist. Disainiteaduslikku uuringut saab põhjendada ka teiste filosoofiliste seisukohtade kaudu.')],
      methodology: [choice('design-science', true, 'Build and evaluate an artifact, then explain what the evaluation teaches about solving this class of problem. Coding alone is not the research contribution.', 'Loo ja hinda artefakti ning selgita, mida hindamine õpetab seda tüüpi probleemi lahendamise kohta. Koodi kirjutamine üksi ei ole uurimuslik panus.'), choice('experimental-design', false, 'An experiment could evaluate a specific design decision, but the overall brief centres creating and evaluating an artifact and deriving design knowledge.', 'Eksperiment võiks hinnata konkreetset disainiotsust, kuid kogu ülesanne keskendub artefakti loomisele, hindamisele ja disainialase teadmise saamisele.')],
      collection: [choice('requirements-interview', true, 'Elicit student and staff goals, existing workflows, exceptions, and constraints before agreeing requirements.', 'Selgita enne nõuete kokkuleppimist õpilaste ja töötajate eesmärgid, senised töövood, erandid ja piirangud.'), choice('observation', true, 'Observing the existing lending workflow can also reveal needs and constraints; validate your interpretations with students and staff.', 'Senise laenutustöövoo vaatlemine võib samuti tuua esile vajadused ja piirangud; kontrolli oma tõlgendusi õpilaste ja töötajatega.')],
      collection2: [choice('usability-testing', true, 'Students and staff attempt realistic reservations and returns so you can measure success, time, and errors.', 'Õpilased ja töötajad proovivad realistlikke broneeringuid ja tagastusi, et saaksid mõõta edukust, aega ja vigu.')],
      analysis: [choice('descriptive-statistics', true, 'Summarise the recorded times and errors, keeping unsuccessful tasks visible instead of averaging only successful attempts.', 'Võta kokku talletatud ajad ja vead, jättes nähtavaks ka ebaõnnestunud ülesanded, mitte keskmistades ainult edukaid katseid.'), choice('thematic-analysis', false, 'Themes can help analyse interview material, but this slot explicitly asks for a summary of measured times and errors.', 'Teemad aitavad analüüsida intervjuumaterjali, kuid siin küsitakse mõõdetud aegade ja vigade kokkuvõtet.')],
      evaluation: [choice('requirements-evaluation', true, 'Agree success criteria before evaluation, compare with the spreadsheet workflow, and explain which design decisions helped and where the prototype falls short.', 'Leppige edukriteeriumid kokku enne hindamist, võrrelge tabelipõhise töövooga ning selgitage, millised disainiotsused aitasid ja kus prototüüp jääb puudulikuks.'), featureFeedback],
    },
  },
];
