import { paradigmCards } from './paradigms';
import { concepts, type Concept } from './foundations';
import { estonianConcepts } from './foundations.et';

type CardText = [string, string, string, string, string, string];
function card(id: string, en: CardText, et: CardText) {
  const make = ([term, cue, definition, question, example, distinction]: CardText): Concept => ({ id, term, cue, definition, question, example, distinction });
  return { en: make(en), et: make(et) };
}
const methodologies = [
  card('case-study', ['Case study', 'A bounded case', 'An in-depth investigation of a bounded case in its real-world context.', 'What can this particular case help us understand?', 'You examine one school’s inclusion programme using interviews, observations, and documents.', 'A case study defines the focus and design; interviews are one possible method within it.'], ['Juhtumiuuring', 'Piiritletud juhtum', 'Piiritletud juhtumi süvitsi uurimine selle tegelikus kontekstis.', 'Mida aitab see konkreetne juhtum mõista?', 'Uurid ühe kooli kaasamisprogrammi intervjuude, vaatluste ja dokumentide abil.', 'Juhtumiuuring määrab uuringu fookuse ja ülesehituse; intervjuu on üks võimalik meetod.']),
  card('experimental-design', ['Experimental design', 'Testing effects', 'Planning a study that manipulates a factor and compares outcomes while controlling alternative explanations.', 'Does changing this feature affect the outcome?', 'You randomly assign users to two error-message designs and compare recovery success on the same tasks.', 'Random assignment supports causal inference; a simple before-and-after comparison may be affected by practice or other changes.'], ['Eksperimentaalne uuring', 'Mõju kontrollimine', 'Uuringu kavandamine, milles muudetakse üht tegurit ja võrreldakse tulemusi, kontrollides alternatiivseid seletusi.', 'Kas selle omaduse muutmine mõjutab tulemust?', 'Määrad kasutajad juhuslikult kahe veateate kujunduse juurde ja võrdled samade ülesannete lahendamise edukust.', 'Juhuslik määramine toetab põhjuslikke järeldusi; lihtsat enne-pärast-võrdlust võib mõjutada harjutamine või muu muutus.']),
  card('ethnography', ['Ethnography', 'Culture in context', 'An approach to understanding a group’s shared practices and meanings through sustained engagement in its setting.', 'How does this group make sense of everyday life?', 'You spend a term in a classroom to understand its routines and unwritten rules.', 'Ethnography involves a broader inquiry into culture; observation alone is a method.'], ['Etnograafia', 'Kultuur kontekstis', 'Lähenemine rühma ühiste tavade ja tähenduste mõistmiseks pikemaajalise osalemise kaudu selle keskkonnas.', 'Kuidas mõtestab see rühm igapäevaelu?', 'Veedad õppeveerandi klassis, et mõista selle rutiine ja kirjutamata reegleid.', 'Etnograafia uurib kultuuri terviklikult; vaatlus üksi on meetod.']),
  card('phenomenology', ['Phenomenology', 'Lived experience', 'An approach that explores the meaning of people’s lived experiences of a phenomenon.', 'What is this experience like for those who live it?', 'You explore how first-year students experience belonging at university.', 'Phenomenology focuses on lived meaning rather than measuring how common an experience is.'], ['Fenomenoloogia', 'Läbielatud kogemus', 'Lähenemine, mis uurib inimeste läbielatud kogemuste tähendust seoses mingi nähtusega.', 'Milline on see kogemus nende jaoks, kes seda läbi elavad?', 'Uurid, kuidas esmakursuslased kogevad ülikoolis kuuluvustunnet.', 'Fenomenoloogia keskendub kogemuse tähendusele, mitte selle leviku mõõtmisele.']),
  card('grounded-theory', ['Grounded theory', 'Building theory', 'An approach that develops theory through iterative data collection and analysis.', 'What explanatory theory can be developed from these data?', 'You alternate interviews and analysis to develop an explanation of how new teachers seek support.', 'Grounded theory aims to develop theory; identifying themes alone does not make a study grounded theory.'], ['Põhistatud teooria', 'Teooria loomine', 'Lähenemine, milles teooriat arendatakse andmete kogumise ja analüüsi korduvate tsüklite kaudu.', 'Millise selgitava teooria saab nende andmete põhjal luua?', 'Vaheldad intervjuusid ja analüüsi, et selgitada, kuidas alustavad õpetajad tuge otsivad.', 'Põhistatud teooria eesmärk on teooria arendamine; üksnes teemade leidmisest ei piisa.']),
  card('mixed-methods', ['Mixed methods research', 'Integrating evidence', 'An approach that integrates quantitative and qualitative evidence within a study.', 'How can numerical patterns and contextual accounts inform each other?', 'You combine survey results with interviews to explain an unexpected pattern in student engagement.', 'Mixed methods requires integration; merely collecting two kinds of data is not enough.'], ['Segameetoditega uuring', 'Tõendite ühendamine', 'Lähenemine, mis lõimib ühe uuringu raames kvantitatiivseid ja kvalitatiivseid tõendeid.', 'Kuidas saavad arvulised mustrid ja kontekstipõhised kirjeldused teineteist täiendada?', 'Ühendad küsitlustulemused intervjuudega, et selgitada ootamatut mustrit õpilaste kaasatuses.', 'Segameetoditega uuring eeldab lõimimist; pelgalt kahte liiki andmete kogumisest ei piisa.']),
  card('action-research', ['Action research', 'Improving practice', 'An approach linking inquiry and practical change through cycles of planning, action, observation, and reflection.', 'How can we improve this practice and learn from the change?', 'A teacher tests a feedback routine, studies its effects, and revises it with learners.', 'Action research combines change with systematic inquiry; simply changing a routine is not enough.'], ['Tegevusuuring', 'Praktika parandamine', 'Lähenemine, mis seob uurimise ja praktilise muutuse kavandamise, tegutsemise, vaatlemise ning refleksiooni tsüklites.', 'Kuidas saame praktikat parandada ja muutusest õppida?', 'Õpetaja katsetab tagasisideviisi, uurib selle mõju ning täiendab seda koos õppijatega.', 'Tegevusuuring ühendab muutuse süstemaatilise uurimisega; pelgalt rutiini muutmisest ei piisa.']),
  card('design-science', ['Design science research', 'Build and evaluate', 'Developing research knowledge by designing and evaluating an artifact that addresses a real problem.', 'What can building and evaluating this solution teach us?', 'You build a lab lending prototype, evaluate it against agreed requirements, and explain which design decisions helped.', 'A working application alone is not a research contribution; systematic evaluation and transferable design insights matter.'], ['Disainiteaduslik uuring', 'Loomine ja hindamine', 'Uurimusliku teadmise loomine tegelikku probleemi lahendava artefakti kavandamise ja hindamise kaudu.', 'Mida õpetab selle lahenduse loomine ja hindamine?', 'Lood labori laenutusrakenduse prototüübi, hindad seda kokkulepitud nõuete alusel ja selgitad, millised disainiotsused aitasid.', 'Töötav rakendus üksi ei ole uurimuslik panus; olulised on süstemaatiline hindamine ja ülekantavad disainialased teadmised.']),
];
const methods = [
  card('observation', ['Observation', 'Watching practice', 'Systematically watching and recording activities, interactions, or events.', 'What happens in this setting?', 'You record how often and in what ways students contribute during group work.', 'Observation records what is observable; motives may require other evidence.'], ['Vaatlus', 'Tegevuse jälgimine', 'Tegevuste, suhtluse või sündmuste süstemaatiline jälgimine ja talletamine.', 'Mis selles keskkonnas toimub?', 'Märgid üles, kui sageli ja kuidas õpilased rühmatöös osalevad.', 'Vaatlus talletab jälgitavat; motiivide mõistmiseks võib vaja minna muid tõendeid.']),
  card('interview', ['Interview', 'Asking and listening', 'Collecting research material by asking participants questions in a conversation.', 'How do participants describe their perspectives?', 'You ask students to describe moments when feedback helped them learn.', 'An interview produces accounts of experience; it does not directly observe the events described.'], ['Intervjuu', 'Küsimine ja kuulamine', 'Uurimismaterjali kogumine osalejatele vestluse käigus küsimusi esitades.', 'Kuidas kirjeldavad osalejad oma vaatenurki?', 'Palud õpilastel kirjeldada hetki, mil tagasiside aitas neil õppida.', 'Intervjuu annab kogemuste kirjeldusi; see ei vaatle kirjeldatud sündmusi vahetult.']),
  card('requirements-interview', ['Requirements interview', 'Discovering needs', 'A focused interview to elicit stakeholders’ goals, workflows, constraints, and needs for a proposed system.', 'What problem must the system solve for its users?', 'You interview students and lab staff about reservations, equipment returns, and exceptions before defining requirements.', 'This is a specialised interview purpose. Requested features need clarification and validation; they are not automatically the best solution.'], ['Nõuete intervjuu', 'Vajaduste väljaselgitamine', 'Sihipärane intervjuu kavandatava süsteemi osapoolte eesmärkide, töövoogude, piirangute ja vajaduste väljaselgitamiseks.', 'Millise probleemi peab süsteem kasutajate jaoks lahendama?', 'Intervjueerid enne nõuete määratlemist õpilasi ja laboritöötajaid broneeringute, tagastuste ja erandite kohta.', 'See on kindla eesmärgiga intervjuu. Soovitud funktsioonid vajavad täpsustamist ja kontrollimist ega ole automaatselt parim lahendus.']),
  card('focus-group', ['Focus group', 'Group discussion', 'Collecting research material through a facilitated discussion among participants.', 'How do perspectives emerge through group interaction?', 'A moderator invites students to discuss assessment and respond to one another’s ideas.', 'Interaction between participants is central; a focus group is more than separate interviews held together.'], ['Fookusrühm', 'Rühmaarutelu', 'Uurimismaterjali kogumine osalejate juhendatud rühmaarutelu kaudu.', 'Kuidas kujunevad vaatenurgad rühma suhtluses?', 'Moderaator kutsub õpilasi hindamist arutama ja üksteise mõtetele vastama.', 'Osalejate omavaheline suhtlus on keskne; fookusrühm ei ole lihtsalt mitu intervjuud korraga.']),
  card('questionnaire', ['Questionnaire', 'Structured questions', 'Collecting responses through a set of written questions.', 'What can the same questions tell us across participants?', 'Students complete a form with rating scales and open questions about feedback.', 'A questionnaire is an instrument; a survey is a broader process of collecting and analysing responses.'], ['Küsimustik', 'Kirjalikud küsimused', 'Vastuste kogumine kirjalike küsimuste komplekti abil.', 'Mida näitavad samad küsimused eri osalejate kohta?', 'Õpilased täidavad tagasiside kohta hindamisskaalade ja avatud küsimustega vormi.', 'Küsimustik on andmekogumisvahend; küsitlusuuring hõlmab laiemat kogumise ja analüüsi protsessi.']),
  card('usability-testing', ['Usability testing', 'Real tasks with users', 'Evaluating an interface by observing representative users attempting realistic tasks.', 'Can intended users complete their tasks, and where do they struggle?', 'Students use a room-finder prototype while you record task success, time, errors, and their comments.', 'Usability testing examines interaction with a product; passing software unit tests does not establish usability.'], ['Kasutatavuse testimine', 'Kasutajate tegelikud ülesanded', 'Kasutajaliidese hindamine sihtrühma esindajate realistlike ülesannete täitmist jälgides.', 'Kas sihtkasutajad saavad ülesannetega hakkama ja kus tekivad raskused?', 'Õpilased kasutavad ruumiotsingu prototüüpi ning talletad ülesande edukuse, aja, vead ja kommentaarid.', 'Kasutatavuse testimine uurib tootega suhtlemist; tarkvara ühiktestide läbimine ei tõenda kasutatavust.']),
  card('descriptive-statistics', ['Descriptive statistics', 'Summarising numbers', 'Summarising numerical data using measures and displays such as averages, frequencies, and distributions.', 'What patterns describe the data we collected?', 'You report the median study time and display the distribution of students’ responses.', 'Descriptive statistics summarise observed data; they do not by themselves establish causes or population-wide conclusions.'], ['Kirjeldav statistika', 'Arvandmete kokkuvõte', 'Arvandmete kokkuvõtmine näitajate ja esituste abil, näiteks keskmised, sagedused ja jaotused.', 'Millised mustrid kirjeldavad kogutud andmeid?', 'Esitad õppimisaja mediaani ja õpilaste vastuste jaotuse.', 'Kirjeldav statistika võtab andmed kokku; see ei tõesta iseenesest põhjuseid ega võimalda üldistada kogu populatsioonile.']),
  card('thematic-analysis', ['Thematic analysis', 'Patterns of meaning', 'Analysing qualitative material to develop patterns of meaning across a dataset.', 'What meaningful patterns run through these accounts?', 'You code interview transcripts and develop themes about trust in teacher feedback.', 'Themes are developed through analysis; they are not simply the most frequent words.'], ['Temaatiline analüüs', 'Tähendusmustrid', 'Kvalitatiivse materjali analüüsimine, et arendada kogu andmestikku läbivaid tähendusmustreid.', 'Millised tähenduslikud mustrid neid kirjeldusi läbivad?', 'Kodeerid intervjuude transkriptsioone ja arendad teemasid õpetaja tagasiside usaldamise kohta.', 'Teemad kujunevad analüüsis; need ei ole lihtsalt kõige sagedasemad sõnad.']),
];
export const decks = [
  { id: 'foundations', en: 'Foundations of research', et: 'Uurimistöö alused', description: 'Reality, knowledge, values, and the choices behind a study. Get to know the ideas that connect them.', descriptionEt: 'Tegelikkus, teadmised, väärtused ja uuringu aluseks olevad valikud. Tutvu neid ühendavate mõistetega.', cards: { en: concepts, et: estonianConcepts } },
  { id: 'paradigms', en: 'Paradigms', et: 'Paradigmad', description: 'Explore seven research orientations and their assumptions about reality, knowledge, and values.', descriptionEt: 'Tutvu seitsme uurimissuuna ning nende eeldustega tegelikkuse, teadmiste ja väärtuste kohta.', cards: paradigmCards },
  { id: 'methodologies', en: 'Methodology', et: 'Metodoloogia', description: 'Explore approaches to designing a study, from case studies to mixed methods research.', descriptionEt: 'Tutvu lähenemistega uuringu kavandamisele, juhtumiuuringust segameetoditega uuringuni.', cards: { en: methodologies.map(c => c.en), et: methodologies.map(c => c.et) } },
  { id: 'methods', en: 'Methods', et: 'Meetodid', description: 'Discover practical techniques for collecting and analysing research material.', descriptionEt: 'Avasta praktilisi võtteid uurimismaterjali kogumiseks ja analüüsimiseks.', cards: { en: methods.map(c => c.en), et: methods.map(c => c.et) } },
];
