export interface Concept { id: string; term: string; cue: string; definition: string; question: string; example: string; distinction: string }
export const concepts: Concept[] = [
  { id: 'ontology', term: 'Ontology', cue: 'Reality', definition: 'Assumptions about what exists and the nature of reality.', question: 'What is reality like?', example: 'Before studying belonging, you consider whether it is a single measurable reality or something experienced differently across contexts.', distinction: 'Ontology concerns reality. Epistemology concerns how we can know about it.' },
  { id: 'epistemology', term: 'Epistemology', cue: 'Knowledge', definition: 'Assumptions about knowledge and how we can develop and justify it.', question: 'How can we know about it?', example: 'You consider what test scores and students’ accounts can each tell you about learning, and the limits of that knowledge.', distinction: 'Epistemology informs what counts as evidence. A method specifies how you collect or analyse it.' },
  { id: 'axiology', term: 'Axiology', cue: 'Values', definition: 'The role of values in shaping research aims, conduct, and interpretation.', question: 'How do values shape the research?', example: 'You explain how your commitment to inclusion influenced your research question and whose perspectives you included.', distinction: 'Axiology concerns values throughout research, extending beyond formal ethics approval.' },
  { id: 'paradigm', term: 'Research paradigm', cue: 'Worldview', definition: 'A broad set of assumptions and commitments that guides research.', question: 'What worldview guides this study?', example: 'You adopt an interpretivist worldview, focusing on how students make meaning of their experiences.', distinction: 'A paradigm brings together broad assumptions. A methodology explains the approach to a study.' },
  { id: 'methodology', term: 'Methodology', cue: 'Approach & reasoning', definition: 'The overall approach and reasoning that guide study design and method choices.', question: 'Why is this approach appropriate?', example: 'You explain why ethnography—studying people in their everyday settings—suits your investigation of classroom culture.', distinction: 'Methodology explains the approach and its rationale. Methods are the specific techniques used.' },
  { id: 'method', term: 'Method', cue: 'Techniques', definition: 'A specific technique for collecting or analysing research material.', question: 'How will I collect or analyse evidence?', example: 'You conduct interviews with students or use statistical analysis to examine survey responses.', distinction: 'A method is a practical procedure. The same method can be used within different paradigms.' },
];
export const conceptById = (id: string) => concepts.find(c => c.id === id)!;
