import type { Concept } from './foundations';
export const estonianConcepts: Concept[] = [
  { id: 'ontology', term: 'Ontoloogia', cue: 'Tegelikkus', definition: 'Eeldused selle kohta, mis on olemas ja milline on tegelikkuse olemus.', question: 'Milline on tegelikkus?', example: 'Enne kuuluvustunde uurimist mõtled, kas see on üks mõõdetav nähtus või kogetakse seda eri olukordades erinevalt.', distinction: 'Ontoloogia käsitleb tegelikkust. Epistemoloogia käsitleb seda, kuidas saame tegelikkuse kohta teadmisi.' },
  { id: 'epistemology', term: 'Epistemoloogia', cue: 'Teadmised', definition: 'Eeldused teadmiste ning nende kujundamise ja põhjendamise kohta.', question: 'Kuidas saame selle kohta teadmisi?', example: 'Mõtled, mida saavad testitulemused ja õppijate kirjeldused õppimise kohta öelda ning millised on nende teadmiste piirid.', distinction: 'Epistemoloogia aitab mõtestada, mida pidada tõendusmaterjaliks. Meetod määrab, kuidas seda koguda või analüüsida.' },
  { id: 'axiology', term: 'Aksioloogia', cue: 'Väärtused', definition: 'Väärtuste roll uurimistöö eesmärkide, läbiviimise ja tõlgendamise kujundamisel.', question: 'Kuidas väärtused uurimistööd mõjutavad?', example: 'Selgitad, kuidas kaasamise väärtustamine mõjutas sinu uurimisküsimust ja seda, kelle vaatenurgad uuringusse kaasasid.', distinction: 'Aksioloogia käsitleb väärtusi kogu uurimistöö vältel ega piirdu eetikakomitee heakskiiduga.' },
  { id: 'paradigm', term: 'Uurimisparadigma', cue: 'Maailmavaade', definition: 'Uurimistööd suunavate üldiste eelduste ja põhimõtete kogum.', question: 'Milline maailmavaade seda uuringut suunab?', example: 'Lähtud interpretivistlikust ehk tõlgendavast maailmavaatest ja keskendud sellele, kuidas õppijad oma kogemustele tähendusi annavad.', distinction: 'Paradigma ühendab üldised eeldused. Metodoloogia selgitab uuringu läbiviimise lähenemisviisi.' },
  { id: 'methodology', term: 'Metodoloogia', cue: 'Lähenemisviis ja põhjendus', definition: 'Uuringu kavandamist ja meetodite valikut suunav üldine lähenemisviis koos põhjendustega.', question: 'Miks see lähenemisviis sobib?', example: 'Selgitad, miks etnograafia ehk inimeste uurimine nende igapäevases keskkonnas sobib klassiruumi kultuuri uurimiseks.', distinction: 'Metodoloogia selgitab lähenemisviisi ja selle põhjendust. Meetodid on konkreetsed kasutatavad võtted.' },
  { id: 'method', term: 'Meetod', cue: 'Uurimisvõtted', definition: 'Konkreetne võte uurimismaterjali kogumiseks või analüüsimiseks.', question: 'Kuidas kogun või analüüsin tõendusmaterjali?', example: 'Viid õppijatega läbi intervjuusid või kasutad küsitlusvastuste uurimiseks statistilist analüüsi.', distinction: 'Meetod on praktiline töövõte. Sama meetodit saab kasutada eri paradigmade raames.' },
];
