import type { Concept } from './foundations';

type ParadigmCard = Concept & { assumptions: { ontology: string; epistemology: string; axiology: string } };
export const paradigmCards: { en: ParadigmCard[]; et: ParadigmCard[] } = {
  en: [
    { id: 'interpretivism', term: 'Interpretivism', cue: 'Meaning in context', definition: 'A research orientation focused on understanding how people interpret their experiences in context.', question: 'How do participants make sense of their world?', example: 'You explore how students experience a course-planning app through interviews about their routines and priorities.', distinction: 'Interpretivism focuses on situated meanings. An interview is a method that can also serve other paradigms.', assumptions: { ontology: 'Often treats social realities as multiple and shaped through interpretation and interaction.', epistemology: 'Understanding develops by interpreting participants’ accounts and recognising the researcher’s role.', axiology: 'Researchers reflect on how their own values and position influence interpretation.' } },
    { id: 'pragmatism', term: 'Pragmatism', cue: 'Problems and consequences', definition: 'A research orientation that connects inquiry to practical problems and the consequences of possible solutions.', question: 'Which approach helps us address this problem?', example: 'You combine room-search task results with student interviews to understand whether an app helps and how to improve it.', distinction: 'Pragmatism is not simply choosing whatever is convenient. Choices still need a reasoned justification; mixed methods is not exclusive to this paradigm.', assumptions: { ontology: 'Pragmatic traditions differ; inquiry commonly starts from situations and problems rather than requiring one fixed account of reality.', epistemology: 'Knowledge is developed and revised through inquiry, experience, and examining consequences.', axiology: 'The purposes of inquiry and the consequences for those affected matter when judging a solution.' } },
    { id: 'critical', term: 'Critical / transformative', cue: 'Power and change', definition: 'A family of research orientations that examines power and inequality and seeks to support social change.', question: 'Whose interests are served, and whose voices are missing?', example: 'Students facing accessibility barriers help set priorities, evaluate a planner, and decide which changes matter.', distinction: 'Critical and transformative traditions are diverse. Participatory action research can support their goals, but is not their only methodology.', assumptions: { ontology: 'Social conditions are shaped by historical, cultural, and political relationships, including unequal power.', epistemology: 'Inquiry examines whose knowledge is recognised and how researcher–participant relationships shape understanding.', axiology: 'Values such as inclusion, justice, and reducing oppression are made explicit.' } },
    { id: 'postpositivism', term: 'Postpositivism', cue: 'Evidence with uncertainty', definition: 'A research orientation that investigates a reality beyond our perceptions while treating knowledge of it as fallible and revisable.', question: 'How well does the evidence support this explanation?', example: 'You compare two error-message designs, account for alternative explanations, and report uncertainty about the observed difference.', distinction: 'Postpositivism does not claim that measurement is free of bias or that one experiment proves a theory. It can draw on qualitative as well as quantitative evidence.', assumptions: { ontology: 'A reality exists independently of our accounts, but we can understand it only imperfectly.', epistemology: 'Explanations are tested against evidence and remain open to criticism, error, and revision.', axiology: 'Researchers seek to recognise and reduce bias while acknowledging the influence of values and experience.' } },
    {"id": "positivism", "term": "Positivism", "cue": "Observation and regularities", "definition": "A research orientation that seeks objective knowledge through systematic observation, measurement, and the testing of explanations.", "question": "What measurable regularities can systematic observation establish?", "example": "You test whether a search-interface change reduces errors under controlled conditions, using predefined measures and a repeatable procedure.", "distinction": "Positivism emphasises objective observation. Postpositivism more explicitly treats observations and explanations as fallible. Using numbers alone does not identify a study’s paradigm.", "assumptions": {"ontology": "An independent reality exists and can be investigated through observable regularities.", "epistemology": "Systematic empirical inquiry aims to establish objective explanations.", "axiology": "Researchers aim to keep personal values from influencing observation and analysis."}},
    {"id": "constructivism", "term": "Constructivism", "cue": "Constructing understanding", "definition": "A research orientation in which knowledge and meanings are constructed through experience and interaction; this card emphasises social constructivism.", "question": "How do people develop and negotiate their understanding?", "example": "You explore how student teams negotiate what a “fair contribution” means when designing a shared project dashboard.", "distinction": "Constructivism and interpretivism overlap and are sometimes grouped together. Here, constructivism foregrounds how meanings are constructed; interpretivism foregrounds understanding meanings in context.", "assumptions": {"ontology": "Social realities are understood as multiple and constructed in particular contexts.", "epistemology": "Knowledge develops through interpretation and interaction, including between researchers and participants.", "axiology": "Researchers make their position and its influence on the inquiry explicit."}},
    {"id": "critical-realism", "term": "Critical realism", "cue": "Mechanisms in context", "definition": "A research orientation that seeks to explain outcomes through underlying mechanisms and the conditions in which they operate.", "question": "What could produce this outcome, and under which conditions?", "example": "You investigate why the same booking app reduces staff workload in one department but not another, comparing workflows, permissions, and staff accounts.", "distinction": "Critical realism is distinct from critical/transformative research. It shares postpositivism’s fallibilism but foregrounds mechanisms and context; a recurring theme alone does not establish a causal mechanism.", "assumptions": {"ontology": "Reality includes structures and causal powers that need not be directly observable.", "epistemology": "Explanations of mechanisms are fallible and must be examined against evidence and alternatives.", "axiology": "Researchers reflect on their commitments and examine how their explanatory choices affect those involved."}},
  ],
  et: [
    { id: 'interpretivism', term: 'Interpretivism', cue: 'Tähendus kontekstis', definition: 'Uurimissuund, mis keskendub sellele, kuidas inimesed oma kogemusi kontekstis tõlgendavad.', question: 'Kuidas osalejad oma maailma mõtestavad?', example: 'Uurid intervjuude abil, kuidas õpilased kogevad õppeplaneerijat oma rutiinide ja prioriteetide kaudu.', distinction: 'Interpretivism keskendub kontekstis kujunevatele tähendustele. Intervjuu on meetod, mida saab kasutada ka teistes paradigmades.', assumptions: { ontology: 'Käsitleb sotsiaalset tegelikkust sageli mitmesena ning tõlgendamise ja suhtluse kaudu kujunevana.', epistemology: 'Mõistmine areneb osalejate kirjelduste tõlgendamise ja uurija rolli teadvustamise kaudu.', axiology: 'Uurijad reflekteerivad, kuidas nende väärtused ja positsioon tõlgendamist mõjutavad.' } },
    { id: 'pragmatism', term: 'Pragmatism', cue: 'Probleemid ja tagajärjed', definition: 'Uurimissuund, mis seob uurimise praktiliste probleemide ja võimalike lahenduste tagajärgedega.', question: 'Milline lähenemine aitab seda probleemi lahendada?', example: 'Ühendad ruumiotsingu ülesannete tulemused õpilaste intervjuudega, et mõista rakenduse kasulikkust ja parendusvõimalusi.', distinction: 'Pragmatism ei tähenda lihtsalt mugava valiku tegemist. Valikud vajavad põhjendust; segameetodid ei kuulu ainult sellesse paradigmasse.', assumptions: { ontology: 'Pragmaatilised traditsioonid erinevad; uurimine lähtub sageli olukordadest ja probleemidest, nõudmata üht kindlat tegelikkuse käsitlust.', epistemology: 'Teadmine areneb ja muutub uurimise, kogemuse ning tagajärgede hindamise kaudu.', axiology: 'Lahenduse hindamisel loevad uurimise eesmärgid ja tagajärjed mõjutatud inimestele.' } },
    { id: 'critical', term: 'Kriitiline / transformatiivne', cue: 'Võim ja muutus', definition: 'Uurimissuundade rühm, mis uurib võimu ja ebavõrdsust ning püüab toetada sotsiaalset muutust.', question: 'Kelle huve teenitakse ja kelle hääl puudub?', example: 'Ligipääsetavustakistusi kogevad õpilased aitavad määrata prioriteete, hinnata planeerijat ja otsustada oluliste muutuste üle.', distinction: 'Kriitilised ja transformatiivsed traditsioonid on mitmekesised. Osaluspõhine tegevusuuring võib nende eesmärke toetada, kuid ei ole ainus metodoloogia.', assumptions: { ontology: 'Sotsiaalseid olusid kujundavad ajaloolised, kultuurilised ja poliitilised suhted, sealhulgas ebavõrdne võim.', epistemology: 'Uurimine käsitleb seda, kelle teadmisi tunnustatakse ja kuidas uurija ning osalejate suhted mõistmist kujundavad.', axiology: 'Väärtused nagu kaasamine, õiglus ja rõhumise vähendamine tehakse selgesõnaliseks.' } },
    { id: 'postpositivism', term: 'Postpositivism', cue: 'Tõendid ja ebakindlus', definition: 'Uurimissuund, mis uurib meie tajust sõltumatut tegelikkust, käsitledes teadmisi sellest ekslike ja muudetavatena.', question: 'Kui hästi toetavad tõendid seda selgitust?', example: 'Võrdled kahte veateate kujundust, arvestad alternatiivseid seletusi ja kirjeldad täheldatud erinevusega seotud ebakindlust.', distinction: 'Postpositivism ei väida, et mõõtmine on kallutatuseta või et üks eksperiment tõestab teooria. Kasutada saab nii kvalitatiivseid kui ka kvantitatiivseid tõendeid.', assumptions: { ontology: 'Tegelikkus eksisteerib meie kirjeldustest sõltumatult, kuid saame seda mõista vaid ebatäiuslikult.', epistemology: 'Selgitusi kontrollitakse tõenditega ning need jäävad avatuks kriitikale, eksimustele ja muutmisele.', axiology: 'Uurijad püüavad kallutatust märgata ja vähendada, tunnistades väärtuste ning kogemuse mõju.' } },
    {"id": "positivism", "term": "Positivism", "cue": "Vaatlus ja seaduspärasused", "definition": "Uurimissuund, mis taotleb objektiivseid teadmisi süstemaatilise vaatluse, mõõtmise ja selgituste kontrollimise kaudu.", "question": "Milliseid mõõdetavaid seaduspärasusi saab süstemaatiline vaatlus tuvastada?", "example": "Katsetad kontrollitud tingimustes, kas otsinguliidese muudatus vähendab vigu, kasutades ette määratud mõõdikuid ja korratavat protseduuri.", "distinction": "Positivism rõhutab objektiivset vaatlust. Postpositivism käsitleb vaatlusi ja selgitusi selgemalt eksimisvõimelistena. Arvude kasutamine üksi ei määra uuringu paradigmat.", "assumptions": {"ontology": "Sõltumatu tegelikkus eksisteerib ja seda saab uurida vaadeldavate seaduspärasuste kaudu.", "epistemology": "Süstemaatiline empiiriline uurimine taotleb objektiivseid selgitusi.", "axiology": "Uurijad püüavad vältida isiklike väärtuste mõju vaatlusele ja analüüsile."}},
    {"id": "constructivism", "term": "Konstruktivism", "cue": "Arusaamade kujunemine", "definition": "Uurimissuund, milles teadmised ja tähendused kujunevad kogemuse ja suhtluse kaudu; see kaart rõhutab sotsiaalset konstruktivismi.", "question": "Kuidas inimesed oma arusaamu kujundavad ja läbi räägivad?", "example": "Uurid, kuidas õpilasrühmad ühise projektitöölaua kavandamisel läbi räägivad, mida tähendab „õiglane panus”.", "distinction": "Konstruktivism ja interpretivism kattuvad ning neid käsitletakse vahel koos. Siin rõhutab konstruktivism tähenduste kujunemist, interpretivism aga tähenduste mõistmist kontekstis.", "assumptions": {"ontology": "Sotsiaalseid tegelikkusi mõistetakse mitmesena ja konkreetses kontekstis kujunevana.", "epistemology": "Teadmised arenevad tõlgendamise ja suhtluse, sealhulgas uurija ja osalejate suhtluse kaudu.", "axiology": "Uurijad teevad oma positsiooni ja selle mõju uurimisele selgesõnaliseks."}},
    {"id": "critical-realism", "term": "Kriitiline realism", "cue": "Mehhanismid kontekstis", "definition": "Uurimissuund, mis püüab selgitada tulemusi neid tekitavate mehhanismide ja nende toimimistingimuste kaudu.", "question": "Mis võiks selle tulemuse tekitada ja millistes tingimustes?", "example": "Uurid töövooge, õigusi ja töötajate kirjeldusi võrreldes, miks sama broneerimisrakendus vähendab ühes osakonnas töökoormust, kuid teises mitte.", "distinction": "Kriitiline realism erineb kriitilisest/transformatiivsest uurimisest. See jagab postpositivismi arusaama teadmiste ekslikkusest, kuid rõhutab mehhanisme ja konteksti; korduv teema üksi ei tõenda põhjuslikku mehhanismi.", "assumptions": {"ontology": "Tegelikkus hõlmab struktuure ja põhjuslikke võimeid, mis ei pruugi olla vahetult vaadeldavad.", "epistemology": "Mehhanismide selgitused võivad olla ekslikud ning neid tuleb uurida tõendite ja alternatiivide suhtes.", "axiology": "Uurijad reflekteerivad oma veendumusi ja uurivad, kuidas selgituste valik mõjutab asjaosalisi."}},
  ],
};
// Scenario cards derive from the learning deck so definitions cannot drift apart.
export const paradigms = paradigmCards.en.map((card, index) => ({
  id: card.id,
  term: { en: card.term, et: paradigmCards.et[index].term },
  definition: { en: card.definition, et: paradigmCards.et[index].definition },
}));
