import type { Bilingual, Study } from './studies';
const text = (en: string, et: string): Bilingual => ({ en, et });
const choice = (id: string, fits: boolean, en: string, et: string) => ({ id, fits, reason: text(en, et) });
export const paradigmStudies: Study[] = [
  {
    id: 'search-experiment', title: text('Testing a search interface', 'Otsinguliidese katsetamine'),
    question: text('Does a revised search interface reduce task errors under controlled conditions?', 'Kas uuendatud otsinguliides vähendab kontrollitud tingimustes ülesandevigu?'),
    brief: text('Build two interface versions. Randomly assign participants to a version, use the same tasks and predefined error measures, and hold other conditions constant. Seek an objective test while reporting uncertainty and competing explanations. Both positivist and postpositivist justifications are available; explain your stance. Numerical summaries are supplied as a first descriptive step, not a complete test of the effect.', 'Loo kaks liidese versiooni. Määra osalejad juhuslikult versioonidele, kasuta samu ülesandeid ja ette määratud veamõõdikuid ning hoia muud tingimused samad. Taotle objektiivset kontrolli, kirjeldades ebakindlust ja konkureerivaid selgitusi. Võimalikud on nii positivistlik kui ka postpositivistlik põhjendus; selgita oma seisukohta. Arvulised kokkuvõtted on ette antud esimese kirjeldava sammuna, mitte mõju täieliku kontrollina.'),
    fixed: { analysis: 'descriptive-statistics' },
    slots: {
      paradigm: [choice('postpositivism', true, 'Treat the error difference as fallible evidence: examine uncertainty, measurement limitations, and rival explanations before drawing a conclusion.', 'Käsitle vigade erinevust eksimisvõimelise tõendina: uuri ebakindlust, mõõtmise piiranguid ja alternatiivseid selgitusi enne järeldamist.'), choice('positivism', true, 'The emphasis on controlled observation and objective measurement can support a positivist justification. State that commitment explicitly; the experiment itself does not determine the paradigm.', 'Kontrollitud vaatluse ja objektiivse mõõtmise rõhutamine võib toetada positivistlikku põhjendust. Sõnasta see veendumus selgelt; eksperiment ise ei määra paradigmat.'), choice('constructivism', false, 'Constructivism could guide a different question about how users construct the meaning of an error. This brief instead asks for a controlled test of predefined error counts.', 'Konstruktivism võiks suunata teist küsimust selle kohta, kuidas kasutajad vea tähendust kujundavad. Siin küsitakse aga ette määratud veaarvude kontrollitud katset.')],
      methodology: [choice('experimental-design', true, 'Random assignment and controlled conditions support testing the interface change while reducing alternative explanations.', 'Juhuslik määramine ja kontrollitud tingimused toetavad liidese muudatuse katsetamist ning vähendavad alternatiivseid selgitusi.'), choice('case-study', false, 'A case study could investigate interface use in context, but would not by itself provide the randomised comparison specified here.', 'Juhtumiuuring võiks uurida liidese kasutust kontekstis, kuid ei annaks iseenesest siin nõutud juhuslikustatud võrdlust.')],
      collection: [choice('usability-testing', true, 'Record errors as participants carry out the same realistic tasks with their assigned interface.', 'Talleta vead, kui osalejad täidavad samu realistlikke ülesandeid neile määratud liidesega.'), choice('interview', false, 'Interviews could explain difficulties, but do not replace the observed task-error measurements required for this comparison.', 'Intervjuud võiksid raskusi selgitada, kuid ei asenda selleks võrdluseks nõutud vaadeldud ülesandevigade mõõtmisi.')],
      analysis: [choice('descriptive-statistics', true, 'Summarise errors in each group. Estimating the effect and its uncertainty needs further analysis beyond this introductory card; a difference in averages alone does not settle the hypothesis.', 'Võta iga rühma vead kokku. Mõju ja selle ebakindluse hindamine vajab lisaanalüüsi väljaspool seda sissejuhatavat kaarti; keskmiste erinevus üksi ei lahenda hüpoteesi.')],
    },
  },
  {
    id: 'team-dashboard', title: text('Meaning in a team dashboard', 'Tähendused rühmatöö töölaual'),
    question: text('How do student teams negotiate what “fair contribution” should mean in a project dashboard?', 'Kuidas räägivad õpilasrühmad läbi, mida peaks projektitöölaual tähendama „õiglane panus”?'),
    brief: text('Before building a contribution indicator, study one project team in depth. Discuss contrasting examples of teamwork and explore how students negotiate meanings together. Reflect on how your questions shape the discussion. Interpret shared meanings and disagreements; do not assume that counting commits defines fairness.', 'Enne panusenäitaja loomist uuri üht projektirühma süvitsi. Arutage erinevaid rühmatöö näiteid ja uuri, kuidas õpilased tähendusi ühiselt läbi räägivad. Reflekteeri, kuidas sinu küsimused arutelu kujundavad. Tõlgenda ühiseid tähendusi ja erimeelsusi; ära eelda, et koodimuudatuste loend määratleb õigluse.'),
    fixed: { methodology: 'case-study' },
    slots: {
      paradigm: [choice('constructivism', true, 'Focus on how students construct and negotiate fairness in interaction, including the researcher’s contribution to the discussion.', 'Keskendu sellele, kuidas õpilased suhtluses õiglust kujundavad ja läbi räägivad, sealhulgas uurija panusele arutelus.'), choice('interpretivism', true, 'An interpretivist account can also explore these situated meanings. Explain the emphasis on understanding participants rather than assuming a sharp boundary from constructivism.', 'Interpretivistlik käsitlus võib samuti uurida neid kontekstuaalseid tähendusi. Selgita osalejate mõistmise rõhuasetust, eeldamata järsku piiri konstruktivismiga.'), choice('positivism', false, 'A positivist study could measure a predefined contribution indicator, but this question first asks how the meaning of fairness is constructed.', 'Positivistlik uuring võiks mõõta ette määratud panusenäitajat, kuid see küsimus uurib esmalt õigluse tähenduse kujunemist.')],
      methodology: [choice('case-study', true, 'One project team provides a bounded setting for examining meanings in context.', 'Üks projektirühm pakub piiritletud keskkonda tähenduste uurimiseks kontekstis.')],
      collection: [choice('focus-group', true, 'Group discussion makes agreement, disagreement, and negotiation visible; attend to whose voice dominates.', 'Rühmaarutelu teeb nähtavaks nõustumise, erimeelsused ja läbirääkimise; jälgi, kelle hääl domineerib.'), choice('questionnaire', false, 'Fixed ratings would not replace the interaction and negotiated meanings requested in this brief.', 'Fikseeritud hinnangud ei asenda ülesandes nõutud suhtlust ja läbi räägitud tähendusi.')],
      analysis: [choice('thematic-analysis', true, 'Develop patterns of meaning from the discussion while retaining disagreements and reflecting on your interpretive role.', 'Arenda arutelust tähendusmustreid, säilitades erimeelsused ja reflekteerides oma tõlgendavat rolli.'), choice('descriptive-statistics', false, 'Numerical summaries alone would not explain how students negotiate what fairness means.', 'Arvulised kokkuvõtted üksi ei selgitaks, kuidas õpilased õigluse tähendust läbi räägivad.')],
    },
  },
  {
    id: 'booking-context', title: text('Why a booking app works differently', 'Miks broneerimisrakendus toimib erinevalt'),
    question: text('Why does the same booking app reduce staff workload in one department but not another?', 'Miks vähendab sama broneerimisrakendus ühes osakonnas töötajate koormust, kuid teises mitte?'),
    brief: text('Compare two departmental cases. Interview staff and observe approval workflows, permissions, and exceptions. Use themes to organise accounts, then propose mechanisms that might explain the different outcomes and examine rival explanations against both cases. The mechanism-explanation step goes beyond identifying themes.', 'Võrdle kahe osakonna juhtumeid. Intervjueeri töötajaid ning vaatle kinnitamise töövooge, õigusi ja erandeid. Korrasta kirjeldused teemadeks, seejärel paku välja erinevaid tulemusi selgitada võivaid mehhanisme ja uuri alternatiivseid selgitusi mõlema juhtumi tõendite suhtes. Mehhanismide selgitamine ulatub teemade tuvastamisest kaugemale.'),
    fixed: { collection2: 'observation' },
    slots: {
      paradigm: [choice('critical-realism', true, 'Look beyond the observed difference to mechanisms, such as how permissions and approval routines enable or block work in each context. Treat these as explanations to investigate, not established facts.', 'Vaata täheldatud erinevusest kaugemale mehhanismidele, näiteks sellele, kuidas õigused ja kinnitamisrutiinid igas kontekstis tööd võimaldavad või takistavad. Käsitle neid uuritavate selgituste, mitte tõestatud faktidena.'), choice('critical', false, 'A critical/transformative study could centre unequal power and collective change. This brief centres explaining how mechanisms operate in different contexts; the similar names do not make the orientations identical.', 'Kriitiline/transformatiivne uuring võiks keskenduda ebavõrdsele võimule ja ühisele muutusele. Siinne ülesanne keskendub mehhanismide toimimise selgitamisele eri kontekstides; sarnased nimed ei muuda suundi samaks.')],
      methodology: [choice('case-study', true, 'A comparative case study allows you to examine the app, routines, and conditions within each department.', 'Võrdlev juhtumiuuring võimaldab uurida rakendust, rutiine ja tingimusi igas osakonnas.'), choice('experimental-design', false, 'The brief investigates existing departmental contexts rather than randomly assigning a controlled intervention.', 'Ülesanne uurib olemasolevaid osakondade kontekste, mitte ei määra juhuslikult kontrollitud sekkumist.')],
      collection: [choice('interview', true, 'Staff accounts help identify possible explanations to examine alongside observed workflows.', 'Töötajate kirjeldused aitavad leida võimalikke selgitusi, mida uurida koos vaadeldud töövoogudega.'), choice('questionnaire', false, 'Ratings alone would not supply the detailed accounts of exceptions and routines requested here.', 'Ainult hinnangud ei annaks siin nõutud põhjalikke erandite ja rutiinide kirjeldusi.')],
      collection2: [choice('observation', true, 'Observe how booking and approval actually happen, including workarounds and differences from staff accounts.', 'Vaatle, kuidas broneerimine ja kinnitamine tegelikult toimuvad, sealhulgas kõrvalteid ja erinevusi töötajate kirjeldustest.')],
      analysis: [choice('thematic-analysis', true, 'Use themes as an organising step. Then reason about what mechanisms could generate the outcomes under these conditions and compare alternative explanations; themes are not themselves proof of causation.', 'Kasuta teemasid korrastava sammuna. Seejärel arutle, millised mehhanismid võiksid nendes tingimustes tulemusi tekitada, ja võrdle alternatiivseid selgitusi; teemad ise ei tõenda põhjuslikkust.'), choice('descriptive-statistics', false, 'Workload summaries could document differences, but alone would not analyse the detailed accounts or explain the mechanisms requested here.', 'Töökoormuse kokkuvõtted võiksid erinevusi kirjeldada, kuid üksi ei analüüsiks põhjalikke kirjeldusi ega selgitaks siin otsitavaid mehhanisme.')],
    },
  },
];
