import type { Bilingual } from './studies';
const text = (en: string, et: string): Bilingual => ({ en, et });
export const qualityLessons = [
  { id: 'quality-sampling', title: text('Sampling and participant selection', 'Valim ja osalejate valik'), body: text('Define whom the question concerns and justify whom you include. Probability sampling can support population estimates; purposive selection can provide relevant, varied experiences for qualitative inquiry. A convenient sample is not automatically representative. Random assignment to conditions is different from random sampling.', 'Määra, keda küsimus puudutab, ja põhjenda kaasatavate valikut. Tõenäosuslik valim võib toetada üldkogumi hindamist; eesmärgipärane valik võib anda kvalitatiivseks uurimiseks asjakohaseid ja mitmekesiseid kogemusi. Mugavusvalim ei ole automaatselt esinduslik. Juhuslik tingimustesse määramine erineb juhuvalimist.') },
  { id: 'quality-bias', title: text('Bias and reflexivity', 'Kallutatus ja refleksiivsus'), body: text('Recruitment, prompts, task order, and selective reporting can shape findings. Look for evidence that challenges your preferred explanation. In interpretive work, reflect on how your position shapes the inquiry rather than promising to remove every researcher influence.', 'Värbamine, küsimused, ülesannete järjekord ja valikuline raporteerimine võivad tulemusi kujundada. Otsi tõendeid, mis seavad sinu eelistatud selgituse kahtluse alla. Tõlgendavas töös reflekteeri oma positsiooni mõju, lubamata eemaldada kogu uurija mõju.') },
  { id: 'quality-ethics', title: text('Consent and privacy', 'Nõusolek ja privaatsus'), body: text('Explain the activity, recording, risks, data use, and withdrawal arrangements before seeking voluntary participation. Collect only needed information and plan restricted access and deletion. Removing names does not guarantee anonymity. Follow your institution’s ethics process, including safeguards for children; this lesson is not ethics approval or jurisdiction-specific legal advice.', 'Selgita tegevust, salvestamist, riske, andmekasutust ja loobumise korda enne vabatahtliku osalemise nõusoleku küsimist. Kogu ainult vajalikku teavet ning kavanda piiratud ligipääs ja kustutamine. Nimede eemaldamine ei taga anonüümsust. Järgi oma asutuse eetikakorda, sealhulgas laste kaitsemeetmeid; see õppetund ei ole eetikakooskõlastus ega konkreetse riigi õigusnõuanne.') },
  { id: 'quality-measurement', title: text('Validity and reliability', 'Valiidsus ja reliaablus'), body: text('Validity concerns whether evidence supports the intended interpretation; reliability concerns consistency of measurement. Define task success and timing rules before testing. A consistently recorded feature count still cannot establish usefulness. Consider alternative explanations and the settings to which a claim might apply.', 'Valiidsus puudutab seda, kas tõendid toetavad kavandatud tõlgendust; reliaablus puudutab mõõtmise järjepidevust. Määra enne testimist ülesande edukuse ja ajamõõtmise reeglid. Järjepidevalt talletatud funktsioonide arv ei tõenda siiski kasulikkust. Kaalu alternatiivseid selgitusi ja keskkondi, millele väide võiks laieneda.') },
  { id: 'quality-trust', title: text('Trustworthiness in qualitative inquiry', 'Usaldusväärsus kvalitatiivses uurimises'), body: text('Make interpretations traceable to evidence, retain contrasting accounts, and explain analytical decisions and context. Qualitative traditions differ in their quality criteria: credibility and dependability may be more useful than expecting identical interpretations from every researcher. Participant discussion can inform an interpretation without making agreement a universal test of truth.', 'Seo tõlgendused jälgitavalt tõenditega, säilita vastandlikud kirjeldused ning selgita analüüsiotsuseid ja konteksti. Kvalitatiivsete traditsioonide kvaliteedikriteeriumid erinevad: usutavus ja protsessi jälgitavus võivad olla kasulikumad kui kõigilt uurijatelt identsete tõlgenduste ootamine. Arutelu osalejatega võib tõlgendust täiendada, muutmata nõustumist üldkehtivaks tõekriteeriumiks.') },
  { id: 'quality-limits', title: text('Limitations and scope', 'Piirangud ja järelduste ulatus'), body: text('State which people, tasks, and settings the evidence covers and what remains uncertain. A small contextual study can offer useful insight without estimating how common something is in a population. Testing with some disabled users informs accessibility work but does not establish accessibility for everyone.', 'Kirjelda, milliseid inimesi, ülesandeid ja keskkondi tõendid hõlmavad ning mis jääb ebakindlaks. Väike kontekstuaalne uuring võib anda kasulikke teadmisi, hindamata nähtuse levikut üldkogumis. Mõnede puudega kasutajatega testimine toetab ligipääsetavuse tööd, kuid ei tõenda ligipääsetavust kõigile.') },
];
export interface QualityChoice { id: string; label: Bilingual; fits: boolean; feedback: Bilingual }
export interface QualityDecision { id: string; lesson: string; prompt: Bilingual; choices: QualityChoice[] }
const decision = (id: string, lesson: string, prompt: Bilingual, good: Bilingual, bad: Bilingual, explanation: Bilingual): QualityDecision => ({ id, lesson, prompt, choices: [
  { id: 'shortcut', label: bad, fits: false, feedback: text('Reconsider. ', 'Mõtle uuesti. ') },
  { id: 'justified', label: good, fits: true, feedback: explanation },
].map(c => ({ ...c, feedback: c.fits ? explanation : text(c.feedback.en + explanation.en, c.feedback.et + explanation.et) })) });
const common: QualityDecision[] = [
  decision('participants', 'quality-sampling', text('You can easily recruit your friends. What should guide participant selection for this brief?', 'Sõpru on lihtne kaasata. Mis peaks selle ülesande osalejate valikut suunama?'), text('Define relevant users or participants, seek experiences needed for the question, and report recruitment gaps.', 'Määra asjakohased kasutajad või osalejad, otsi küsimuseks vajalikke kogemusi ja kirjelda värbamise lünki.'), text('Recruit the easiest volunteers and describe them as representative of everyone.', 'Kaasa kõige kättesaadavamad vabatahtlikud ja kirjelda neid kõigi esindajatena.'), text('Selection needs a purpose linked to this research question. Convenience can be practical, but does not establish representativeness; explain who is missing and how that affects the claim.', 'Valik vajab selle uurimisküsimusega seotud eesmärki. Mugavus võib olla praktiline, kuid ei tõenda esinduslikkust; selgita, kes puudub ja kuidas see väidet mõjutab.')),
  decision('consent', 'quality-ethics', text('You want to record participant sessions. Which plan better protects participants?', 'Soovid osalejate seansse salvestada. Milline plaan kaitseb osalejaid paremini?'), text('Explain recording and data use, seek voluntary consent, minimise identifiers, and agree access and retention.', 'Selgita salvestamist ja andmekasutust, küsi vabatahtlik nõusolek, vähenda tuvastavaid andmeid ning lepi kokku ligipääs ja säilitamine.'), text('Treat attendance as consent and keep named recordings indefinitely for future projects.', 'Käsitle kohalolekut nõusolekuna ja säilita nimelised salvestised tulevaste projektide jaoks tähtajatult.'), text('Participation should be an informed choice. Explain withdrawal arrangements and limits to confidentiality; a teacher’s or manager’s permission does not replace the participant safeguards required by your institution.', 'Osalemine peaks olema teadlik valik. Selgita loobumise korda ja konfidentsiaalsuse piire; õpetaja või juhi luba ei asenda asutuse nõutud osalejate kaitsemeetmeid.')),
  decision('scope', 'quality-limits', text('The findings look promising. How should you report them?', 'Tulemused näivad paljulubavad. Kuidas peaksid neid esitama?'), text('Describe the sample, context, contradictory evidence, and remaining uncertainty alongside the useful findings.', 'Kirjelda koos kasulike tulemustega valimit, konteksti, vastuolulisi tõendeid ja allesjäänud ebakindlust.'), text('Present the preferred result as universally true and omit unsuccessful or contradictory cases.', 'Esita eelistatud tulemus üldkehtiva tõena ning jäta ebaõnnestunud või vastuolulised juhtumid välja.'), text('A useful result can have a limited scope. Readers need enough context to judge its relevance elsewhere; selective reporting hides the evidence needed to assess the claim.', 'Kasuliku tulemuse ulatus võib olla piiratud. Lugejad vajavad piisavat konteksti selle asjakohasuse hindamiseks mujal; valikuline raporteerimine peidab väite hindamiseks vajalikud tõendid.')),
];
const contextual: Record<string, QualityDecision> = {
  belonging: decision('belonging-voices', 'quality-trust', text('Only the most confident students describe feeling welcome. What strengthens the interpretation?', 'Ainult kõige enesekindlamad õpilased kirjeldavad teretulnud olemist. Mis tugevdab tõlgendust?'), text('Seek less-heard experiences and retain accounts that challenge the main interpretation.', 'Otsi vähem kuuldud kogemusi ja säilita peamist tõlgendust vaidlustavad kirjeldused.'), text('Use the confident students’ agreement as proof that everyone belongs.', 'Kasuta enesekindlate õpilaste üksmeelt tõendina, et kõik tunnevad kuuluvust.'), text('The question concerns experiences in this school. Contrasting accounts help examine the interpretation; agreement among a visible subgroup cannot speak for every student.', 'Küsimus puudutab kogemusi selles koolis. Vastandlikud kirjeldused aitavad tõlgendust uurida; nähtava alarühma üksmeel ei saa rääkida kõigi õpilaste eest.')),
  feedback: decision('feedback-disagreement', 'quality-bias', text('Interview themes contradict the questionnaire pattern. What should you do?', 'Intervjuude teemad on küsimustiku mustriga vastuolus. Mida peaksid tegema?'), text('Examine who answered each part and investigate the disagreement during integration.', 'Uuri, kes vastas kummalegi osale, ja käsitle vastuolu lõimimisel.'), text('Discard the interviews so the numerical result stays clear.', 'Jäta intervjuud välja, et arvuline tulemus jääks selgeks.'), text('Conflicting evidence is informative. Check differences in participants, questions, and context instead of selecting only evidence that supports the preferred account.', 'Vastuolulised tõendid on informatiivsed. Kontrolli osalejate, küsimuste ja konteksti erinevusi, valimata ainult eelistatud selgitust toetavaid tõendeid.')),
  participation: decision('participation-counts', 'quality-measurement', text('Two observers count classroom participation differently. What should happen before comparing cycles?', 'Kaks vaatlejat loendavad klassis osalemist erinevalt. Mida teha enne tsüklite võrdlemist?'), text('Define what counts as participation, pilot the recording procedure, and discuss what counts miss.', 'Määra, mida loetakse osalemiseks, katseta talletamisviisi ja aruta, mis jääb arvudest välja.'), text('Use whichever observer reports the largest improvement.', 'Kasuta selle vaatleja tulemusi, kes teatab suurimast paranemisest.'), text('Consistent recording supports comparison, but frequency is not a complete measure of equitable participation. Discuss the counts with participants’ perspectives.', 'Järjepidev talletamine toetab võrdlust, kuid sagedus ei mõõda võrdset osalemist terviklikult. Aruta arve koos osalejate vaatenurkadega.')),
  'room-finder': decision('room-order', 'quality-bias', text('Everyone tries the old process first and the app second. What threatens the comparison?', 'Kõik proovivad esmalt vana protsessi ja seejärel rakendust. Mis ohustab võrdlust?'), text('Practice may improve the second attempt; vary order appropriately and report remaining limitations.', 'Harjutamine võib teist katset parandada; varieeri järjekorda sobivalt ja kirjelda allesjäänud piiranguid.'), text('Any faster second attempt must be caused by the app.', 'Iga kiirem teine katse peab olema põhjustatud rakendusest.'), text('Order and practice can offer alternative explanations. Comparable tasks and attention to order strengthen the comparison, without removing all uncertainty.', 'Järjekord ja harjutamine võivad anda alternatiivseid selgitusi. Võrreldavad ülesanded ja tähelepanu järjekorrale tugevdavad võrdlust, eemaldamata kogu ebakindlust.')),
  'accessible-planner': decision('planner-selection', 'quality-sampling', text('One mouse user completes the planner tasks. What is the next recruitment decision?', 'Üks hiirt kasutav inimene täidab planeerija ülesanded. Milline on järgmine värbamisotsus?'), text('Include intended users with relevant access tools and barriers, alongside an accessibility review.', 'Kaasa sihtkasutajaid asjakohaste abivahendite ja takistustega ning tee ligipääsetavuse ülevaatus.'), text('Stop testing because one successful user establishes accessibility.', 'Lõpeta testimine, sest ühe kasutaja edu tõendab ligipääsetavust.'), text('Different access needs can reveal different barriers. User testing and accessibility review complement each other; this sample cannot establish universal accessibility.', 'Erinevad ligipääsuvajadused võivad tuua esile erinevaid takistusi. Kasutajatestid ja ligipääsetavuse ülevaatus täiendavad teineteist; see valim ei tõenda üldist ligipääsetavust.')),
  'equipment-lending': decision('lending-failures', 'quality-measurement', text('Some reservation tasks fail. How should you summarise completion time?', 'Mõned broneerimisülesanded ebaõnnestuvad. Kuidas peaksid sooritusaega kokku võtma?'), text('Report failures and the timing rule alongside times for completed tasks.', 'Esita ebaõnnestumised ja ajamõõtmise reegel koos lõpetatud ülesannete aegadega.'), text('Remove failed tasks silently and report only the fast successful attempts.', 'Eemalda ebaõnnestunud ülesanded selgituseta ja esita ainult kiired edukad katsed.'), text('A fast average among successes can conceal an unusable workflow. Readers need success rates and clear timing rules to interpret staff-effort claims.', 'Edukate katsete kiire keskmine võib peita kasutamiskõlbmatu töövoo. Lugejad vajavad edukuse määra ja selgeid ajamõõtmise reegleid, et tõlgendada töötajate ajakulu väiteid.')),
  'search-experiment': decision('search-assignment', 'quality-sampling', text('You randomly assign volunteers to interface versions. What does that establish about recruitment?', 'Määrad vabatahtlikud juhuslikult liidese versioonidele. Mida see värbamise kohta tõendab?'), text('Assignment supports the comparison, but volunteers may still differ from the target population.', 'Määramine toetab võrdlust, kuid vabatahtlikud võivad endiselt erineda sihtkogumist.'), text('Random assignment makes the volunteers a representative random sample of all users.', 'Juhuslik määramine teeb vabatahtlikest kõigi kasutajate esindusliku juhuvalimi.'), text('Assignment concerns which condition a recruited person receives; sampling concerns who enters the study. They address different design questions.', 'Määramine puudutab seda, millise tingimuse värvatud inimene saab; valim puudutab seda, kes uuringusse satub. Need käsitlevad erinevaid disainiküsimusi.')),
  'team-dashboard': decision('dashboard-role', 'quality-trust', text('Your wording suggests that more commits means a fairer contribution. How should you respond?', 'Sinu sõnastus vihjab, et rohkem koodimuudatusi tähendab õiglasemat panust. Kuidas peaksid reageerima?'), text('Reflect on that assumption, use open prompts, and analyse contrasting meanings of fairness.', 'Reflekteeri seda eeldust, kasuta avatud küsimusi ja analüüsi õigluse vastandlikke tähendusi.'), text('Treat agreement with your wording as independent confirmation of the dashboard metric.', 'Käsitle sinu sõnastusega nõustumist töölaua mõõdiku sõltumatu kinnitusena.'), text('The researcher helps shape the discussion. Making that role explicit and retaining disagreements supports an accountable interpretation rather than a claim of neutral discovery.', 'Uurija aitab arutelu kujundada. Selle rolli selgitamine ja erimeelsuste säilitamine toetab põhjendatavat tõlgendust, mitte neutraalse avastuse väidet.')),
  'booking-context': decision('booking-rivals', 'quality-trust', text('Staff mention permissions as a possible cause of delays. What strengthens this explanation?', 'Töötajad nimetavad õigusi võimaliku viivituste põhjusena. Mis tugevdab seda selgitust?'), text('Compare accounts with observed workflows in both departments and examine rival mechanisms.', 'Võrdle kirjeldusi mõlema osakonna vaadeldud töövoogudega ja uuri alternatiivseid mehhanisme.'), text('Treat a recurring interview theme as proof of the causal mechanism.', 'Käsitle korduvat intervjuuteemat põhjusliku mehhanismi tõendina.'), text('A proposed mechanism needs examination against contextual evidence and alternatives. Repetition in accounts alone does not establish causation.', 'Pakutud mehhanismi tuleb uurida kontekstuaalsete tõendite ja alternatiivide suhtes. Kirjelduste korduvus üksi ei tõenda põhjuslikkust.')),
};
export function qualityDecisions(studyId: string): QualityDecision[] {
  return contextual[studyId] ? [common[0], contextual[studyId], common[1], common[2]] : common;
}
